// src/rules/injection-en.ts — English prompt injection detection rules

import type { InjectionRule } from '../types.js'

export const INJECTION_RULES_EN: InjectionRule[] = [
  {
    id: 'en_ignore_prev',
    name: 'Ignore previous instructions',
    pattern: 'ignore\\s+(?:all\\s+)?(?:previous|prior|above|earlier|preceding)\\s+(?:instructions?|rules?|prompts?|guidelines?|constraints?)',
    flags: 'i',
    riskScore: 40,
    category: 'override',
  },
  {
    id: 'en_new_role',
    name: 'Role hijack',
    pattern: '(?:you\\s+are\\s+now|from\\s+now\\s+on\\s+you\\s+are|act\\s+as|pretend\\s+(?:to\\s+be|you\\s+are)|imagine\\s+you\\s+are)\\s+(?:a\\s+)?',
    flags: 'i',
    riskScore: 35,
    category: 'role_hijack',
  },
  {
    id: 'en_system_prompt',
    name: 'System prompt extraction',
    pattern: '(?:output|print|show|reveal|display|repeat|leak|dump)\\s+(?:your\\s+)?(?:system|initial|original|full)?\\s*(?:prompt|instructions?|rules?|guidelines?)',
    flags: 'i',
    // High-confidence single signal — legit users rarely ask to dump the prompt.
    riskScore: 40,
    category: 'exfiltration',
  },
  {
    id: 'en_disregard',
    name: 'Disregard prior context',
    pattern: 'disregard\\s+(?:the\\s+)?(?:above|previous|prior|earlier|preceding|all|these|those)',
    flags: 'i',
    riskScore: 40,
    category: 'override',
  },
  {
    id: 'en_no_guidelines',
    name: 'Operate without guidelines',
    pattern: '(?:no|without|free\\s+of|free\\s+from)\\s+(?:ethical\\s+|content\\s+|safety\\s+)?(?:guidelines?|content\\s+policy|restrictions?|filters?|guardrails?|limitations?)',
    flags: 'i',
    riskScore: 30,
    category: 'override',
  },
  {
    id: 'en_developer_mode',
    name: 'Developer/admin mode',
    pattern: '(?:enter|enable|activate|switch\\s+to)\\s+(?:developer|debug|admin|root|sudo|maintenance|god)\\s+(?:mode|access|privileges?)',
    flags: 'i',
    riskScore: 35,
    category: 'privilege_escalation',
  },
  {
    id: 'en_no_restriction',
    name: 'Remove restrictions',
    pattern: '(?:remove|disable|turn\\s+off|bypass|ignore|skip|override|circumvent)\\s+(?:all\\s+|your\\s+|the\\s+)?(?:safety\\s+|content\\s+)?(?:restrictions?|constraints?|safety|filters?|guardrails?|limitations?|safeguards?|guidelines?|rules?|policy)',
    flags: 'i',
    riskScore: 40,
    category: 'override',
  },
  {
    id: 'en_new_instructions',
    name: 'New/updated instructions marker',
    pattern: '(?:^|[\\n.])\\s*(?:new|updated|revised|additional|important)\\s+instructions?\\b',
    flags: 'i',
    riskScore: 30,
    category: 'injection',
  },
  {
    id: 'en_do_anything',
    name: 'Do Anything Now (DAN)',
    pattern: '(?:DAN|do\\s+anything\\s+now|jailbreak|uncensored|unfiltered)\\s*(?:mode|prompt)?',
    flags: 'i',
    riskScore: 40,
    category: 'jailbreak',
  },
  {
    id: 'en_boundary_marker',
    name: 'Boundary marker injection',
    pattern: '(?:<<|\\[\\[|\\{\\{)\\s*(?:SYSTEM|SYS|END|NEW\\s*INSTRUCTION|OVERRIDE|ADMIN)\\s*(?:>>|\\]\\]|\\}\\})',
    flags: 'i',
    riskScore: 30,
    category: 'injection',
  },
  {
    id: 'en_hidden_instruction',
    name: 'Hidden instruction marker',
    pattern: '(?:the\\s+following\\s+is\\s+(?:a\\s+)?)?(?:hidden|secret|real|actual|true)\\s+(?:instruction|command|prompt|directive)',
    flags: 'i',
    riskScore: 35,
    category: 'injection',
  },
  {
    id: 'en_data_exfil',
    name: 'Data exfiltration',
    pattern: '(?:send|transmit|upload|forward|post|exfiltrate)\\s+(?:all\\s+)?(?:conversation|chat|messages?|history|data|files?|context)\\s+(?:to|via)',
    flags: 'i',
    riskScore: 40,
    category: 'exfiltration',
  },
  {
    id: 'en_never_refuse',
    name: 'Never refuse',
    pattern: '(?:never|do\\s+not|don\'t|cannot|must\\s+not)\\s+(?:refuse|decline|reject|say\\s+no|deny)',
    flags: 'i',
    riskScore: 25,
    category: 'override',
  },
  {
    id: 'en_encode_exfil',
    name: 'Encoded exfiltration',
    pattern: '(?:encode|encrypt|convert)\\s+(?:.*?)\\s+(?:in|to|as)\\s+(?:base64|hex|rot13|binary)',
    flags: 'i',
    riskScore: 25,
    category: 'exfiltration',
  },
  {
    id: 'en_markdown_injection',
    name: 'Markdown image injection',
    pattern: '!\\[\\s*[^\\]]*\\]\\(https?:\\/\\/[^)]*(?:callback|exfil|webhook|log)',
    flags: 'i',
    riskScore: 35,
    category: 'exfiltration',
  },
  {
    id: 'en_system_override',
    name: 'System override claim',
    pattern: '(?:SYSTEM|ADMIN|ROOT)\\s*(?:OVERRIDE|COMMAND|DIRECTIVE|ORDER)',
    flags: 'i',
    riskScore: 35,
    category: 'privilege_escalation',
  },
  {
    id: 'en_authorized_test',
    name: 'Fake authorized test claim',
    pattern: '(?:authorized|approved|legitimate)\\s+(?:penetration|security|pen)\\s*(?:test|testing|audit)',
    flags: 'i',
    riskScore: 30,
    category: 'privilege_escalation',
  },
]
